"""A download of an export is the file that was generated, byte for byte.

The download used to re-render the rows from the live tables. A person renamed
after the export changed the bytes, the recorded hash no longer matched, and
the disclosure record could not produce the file the processor was actually
given. The bytes are now kept at generation and served back as they were.
"""

from __future__ import annotations

from typing import Any

import pytest

from cmp.core.security import file_hash, new_token, token_fingerprint
from cmp.db.repositories import exchange as exchange_repo
from cmp.domain.consent import service as consent_service
from cmp.domain.exchange import service as exchange_service
from cmp.infrastructure.storage import service as storage_service
from cmp.infrastructure.storage.local import LocalFileStorage

pytestmark = pytest.mark.integration


@pytest.fixture
def tmp_storage(tmp_path: Any, monkeypatch: pytest.MonkeyPatch) -> LocalFileStorage:
    store = LocalFileStorage(root=str(tmp_path))
    monkeypatch.setattr(storage_service, "storage", lambda: store)
    return store


async def _consent(conn: Any, seeded: dict[str, Any]) -> None:
    raw = new_token()
    await conn.execute(
        """INSERT INTO consent_link (notice_id, site_id, token, expires_at, created_by)
           VALUES (%s, %s, %s, now() + interval '1 day', %s)""",
        (
            seeded["notice"]["notice_id"],
            seeded["site"]["site_id"],
            token_fingerprint(raw)[:64],
            seeded["users"]["dco"]["id"],
        ),
    )
    await consent_service.serve_notice(
        conn, token=raw, language_code="english", user_id=seeded["subject"]["id"]
    )
    await consent_service.capture(
        conn,
        token=raw,
        user_id=seeded["subject"]["id"],
        language_code="english",
        grants={str(seeded["purpose"]["purpose_uuid"]): True},
        action_type="checkbox_click",
        ip_address="127.0.0.1",
    )


class TestSnapshot:
    async def test_the_download_is_the_generated_bytes_even_after_a_rename(
        self, conn: Any, seeded: dict[str, Any], tmp_storage: LocalFileStorage
    ) -> None:
        await _consent(conn, seeded)
        dpo = seeded["users"]["dpo"]["id"]
        export = await exchange_service.generate(
            conn, project_uuid=str(seeded["project"]["project_uuid"]), actor_id=dpo, role="dpo"
        )
        assert export["file_ref"], "the generated bytes must be kept"

        await conn.execute(
            "UPDATE auth_user SET full_name = 'Renamed After Export' WHERE id = %s",
            (seeded["subject"]["id"],),
        )

        row = await exchange_repo.export_by_uuid(
            conn, str(export["export_uuid"]), role="dpo", user_id=dpo
        )
        assert row is not None
        payload, media_type, _ = await exchange_service.render(conn, row)
        assert media_type == "text/csv"
        assert file_hash(payload.encode("utf-8")) == export["file_hash"]
        assert "Renamed After Export" not in payload

    async def test_a_formula_shaped_name_is_written_as_text(
        self, conn: Any, seeded: dict[str, Any], tmp_storage: LocalFileStorage
    ) -> None:
        await conn.execute(
            "UPDATE auth_user SET full_name = %s WHERE id = %s",
            ('=HYPERLINK("http://evil.example","click")', seeded["subject"]["id"]),
        )
        await _consent(conn, seeded)
        dpo = seeded["users"]["dpo"]["id"]
        export = await exchange_service.generate(
            conn, project_uuid=str(seeded["project"]["project_uuid"]), actor_id=dpo, role="dpo"
        )
        row = await exchange_repo.export_by_uuid(
            conn, str(export["export_uuid"]), role="dpo", user_id=dpo
        )
        assert row is not None
        payload, _, _ = await exchange_service.render(conn, row)
        assert "'=HYPERLINK" in payload
        assert ",=HYPERLINK" not in payload and '"=HYPERLINK' not in payload
