#!/usr/bin/env python3
"""Write docs/domain/pii-fields-and-endpoints.md: the PII columns, then every
endpoint that carries PII, module by module, in the plainest table possible.

Reuses the classifier in personal-data-scan.py so the two documents cannot
disagree about what counts as personal data.

    python3 docs/tools/pii-fields-and-endpoints.py
"""

from __future__ import annotations

import importlib.util
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("scan", ROOT / "docs/tools/personal-data-scan.py")
scan = importlib.util.module_from_spec(spec)
assert spec.loader
spec.loader.exec_module(scan)

#: The 55 columns, table by table. Hand-kept: the database has no flag that
#: says "personal", so this list is the decision, and the value scan in
#: personal-data.md is how it was checked.
COLUMNS: list[tuple[str, list[str]]] = [
    ("auth_user", ["full_name", "email", "secondary_email", "mobile", "username",
                   "organization_id", "dob", "person_type", "role", "password_hash"]),
    ("nomination", ["nominee_name", "nominee_email", "nominee_mobile", "nominee_user_id",
                    "accept_token_hash"]),
    ("rights_request", ["submitted_name", "submitted_contact", "request_text", "verification_note",
                        "refusal_reason", "remedy_text", "response_text", "subject_user_id"]),
    ("rights_request_holder", ["responder_name", "responder_contact", "instruction",
                               "return_summary", "sent_back_reason", "contact_log", "brief"]),
    ("rights_ticket_message", ["body", "evidence_name", "evidence_ref"]),
    ("rights_response_file", ["file_name", "file_ref"]),
    ("consent_artefact", ["ip_address", "auth_user_id"]),
    ("consent_purpose_grant", ["granted"]),
    ("consent_link", ["token", "token_sealed"]),
    ("export_line", ["auth_user_id"]),
    ("export_log", ["file_ref"]),
    ("asset_consent", ["subject_role"]),
    ("data_asset", ["storage_ref"]),
    ("import_batch", ["file_name"]),
    ("processor_respondent", ["name", "contact"]),
    ("person_type_history", ["reason"]),
    ("delegation", ["reason"]),
    ("project_processor", ["decision_reason"]),
    ("project_status_history", ["reason"]),
    ("audit_log", ["actor_user_id", "subject_user_id", "detail_json (holds ip, email)"]),
]

ORDER = ["auth", "me", "public consent", "public information", "rights", "tickets",
         "consent", "exchange", "users", "delegations", "projects", "notices",
         "registry", "messages", "audit", "dashboard"]
TITLE = {
    "auth": "Authentication (`/auth`)", "me": "My own records (`/me`)",
    "public consent": "Consent link (`/c/{token}`)", "public information": "Public rights pages (`/rights`)",
    "rights": "Rights requests — Privacy Office (`/requests`)", "tickets": "Tickets (`/tickets`)",
    "consent": "Consents and links", "exchange": "Exports, imports, collections, assets",
    "users": "Users (`/users`)", "delegations": "Delegations (`/delegations`)",
    "projects": "Projects, approvals, sites", "notices": "Notices",
    "registry": "Purposes, processors, sources", "messages": "Message templates (`/messages`)",
    "audit": "Audit trail (`/audit`)", "dashboard": "Dashboard",
}
METHOD_ORDER = {"GET": 0, "POST": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}


def main() -> None:
    openapi, endpoints, _ = scan.load()
    rows = scan.rows(openapi, endpoints)
    total_cols = sum(len(c) for _, c in COLUMNS)

    out: list[str] = []
    out.append("# PII fields and the APIs that carry them\n")
    out.append("Two lists, kept simple. First the personal columns in the database, table by\n"
               "table. Then every API endpoint that receives or returns personal data, module\n"
               "by module, with the fields named. Generated by\n"
               "`docs/tools/pii-fields-and-endpoints.py`; the reasoning behind each line is in\n"
               "[personal-data.md](personal-data.md).\n")

    out.append(f"## 1. PII fields in the database — {len(COLUMNS)} tables, {total_cols} columns\n")
    out.append("| Table | PII columns |\n|---|---|")
    for table, cols in COLUMNS:
        out.append(f"| `{table}` | " + ", ".join(f"`{c}`" for c in cols) + " |")
    out.append("")
    out.append("**Sealed by DKMS on write** (ciphertext in the row): `full_name`, `email`,\n"
               "`secondary_email`, `mobile`, `username`, `organization_id`, `dob`, `nominee_name`,\n"
               "`nominee_email`, `nominee_mobile`, `submitted_name`, `submitted_contact`,\n"
               "`request_text`, `verification_note`, `refusal_reason`, `remedy_text`,\n"
               "`response_text`, `responder_name`, `responder_contact`, `instruction`,\n"
               "`return_summary`, `sent_back_reason`, `body`, `evidence_name`, `file_name` (both\n"
               "tables), `ip_address`, `name` and `contact` on `processor_respondent`, every\n"
               "`reason`, `decision_reason` — 33 columns. The eight the platform looks rows up\n"
               "by (`email`, `secondary_email`, `mobile`, `username`, `nominee_email`,\n"
               "`nominee_mobile`, `submitted_contact`, and `dob` for the minor test) carry a\n"
               "blind index beside them - `*_idx`, an HMAC of the normalised value - or, for\n"
               "`dob`, the plaintext date `minor_until`, so the lookup works and the value\n"
               "itself is ciphertext.\n\n"
               "**Sealed inside jsonb:** the subject's name and contacts in\n"
               "`rights_request_holder.brief`, and the address on each line of\n"
               "`rights_request_holder.contact_log`, are the sealed values copied as they are.\n\n"
               "**Plaintext by nature** (ids, flags, hashes, storage paths, the rest of the\n"
               "jsonb): the rest. In `audit_log.detail_json` the address is stored as its blind\n"
               "index and no email is written; rows from before that change stand as written,\n"
               "because the trail is hash-chained and cannot be rewritten.\n")

    by = defaultdict(list)
    for r in rows:
        by[r["module"]].append(r)
    public = sum(1 for r in rows if r["anonymous"] != "NO")
    out.append(f"## 2. API endpoints that carry PII — {len(rows)} endpoints in {len(by)} modules\n")
    out.append("Every GET, POST, PUT, PATCH and DELETE whose request or response includes a\n"
               "personal field. *In* is what the caller sends (body, path and query); *out* is\n"
               "what a 2xx response returns. The response carries the value **as stored** — a\n"
               f"sealed column comes back as `SE::…` and the portal decrypts it. {public} of\n"
               "these need no session; they are marked **public**.\n")

    for module in ORDER:
        group = sorted(by.get(module, []), key=lambda r: (r["path"], METHOD_ORDER.get(r["method"], 9)))
        if not group:
            continue
        out.append(f"### {TITLE[module]} — {len(group)} endpoint{'s' if len(group) != 1 else ''}\n")
        out.append("| Method | Endpoint | PII in (request) | PII out (response) |\n|---|---|---|---|")
        for r in group:
            path = f"`{r['path']}`" + (" **public**" if r["anonymous"] != "NO" else "")
            cin = ", ".join(f"`{f}`" for f in r["in"]) or "—"
            cout = ", ".join(f"`{f}`" for f in r["out"]) or "—"
            out.append(f"| {r['method']} | {path} | {cin} | {cout} |")
        out.append("")

    target = ROOT / "docs/domain/pii-fields-and-endpoints.md"
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target.relative_to(ROOT)}: {total_cols} columns, {len(rows)} endpoints")


if __name__ == "__main__":
    sys.exit(main())
